// Cross-engine comparison report renderer (PR 8). Produces a markdown
// document suitable for the README and 1.0 release notes. Three tables:
// throughput, p99 latency, file size — scenarios as rows, the three
// strict-mode engines as columns. Absolute numbers; no ratios.
//
// Reads the same Vec<ScenarioMetrics> the existing render_md consumes,
// so adding this renderer requires zero changes to the discover/load
// path. PR 5/6's data structures are unchanged.

use crate::summary::discover::ScenarioMetrics;
use crate::summary::format::{format_bytes_iec, format_duration_ns};
use crate::summary::metadata::Metadata;

/// Render the cross-engine comparison markdown document.
///
/// `scenarios` is filtered for the three strict-mode engines:
/// chisel-strict, redb-strict, sqlite-strict. Other modes (e.g.
/// future *-unsafe variants if they're ever added to the scenario
/// tier) are ignored — the cross-engine report is strict-only.
pub fn render_cross_engine_markdown(scenarios: &[ScenarioMetrics], metadata: &Metadata) -> String {
    let mut out = String::new();
    out.push_str("# Chisel Bench: Cross-engine comparison\n\n");
    out.push_str(&render_header(metadata));
    out.push('\n');

    // Empty-input early exit per spec §3.2.
    if scenarios.is_empty() {
        out.push_str("No scenario data available — run `cargo bench --bench scenarios` first.\n");
        return out;
    }

    out.push_str(render_scenarios_section());
    out.push('\n');
    out.push_str(&render_throughput_table(scenarios));
    out.push('\n');
    out.push_str(&render_p99_table(scenarios));
    out.push('\n');
    out.push_str(&render_file_size_table(scenarios));
    out.push('\n');
    out.push_str(render_methodology_footer());
    out
}

fn render_header(metadata: &Metadata) -> String {
    format!(
        "Generated by chisel-bench-summarize at {}.\n\
         Machine: {} {} {}; Chisel commit {}.\n\
         \n\
         Three engines, all in their **Strict durability mode** (every commit\n\
         fsynced through the disk's write cache). On macOS, `SqliteEngine` uses\n\
         `PRAGMA fullfsync=ON` so its fsync semantics match Chisel's `sync_all`\n\
         (`fcntl(F_FULLFSYNC)`); on Linux the pragma is a no-op.\n\
         \n\
         Cache size: 256 pages (2 MiB) for all three engines.\n",
        metadata.timestamp,
        metadata.machine.os,
        metadata.machine.arch,
        metadata.machine.hostname,
        metadata.chisel_commit,
    )
}

fn render_scenarios_section() -> &'static str {
    "## Scenarios\n\
     \n\
     - **YCSB-A** — 50/50 read/update mix, Zipfian access (θ=0.99). 100K records × 1 KiB.\n\
     - **YCSB-B** — 95/5 read-heavy, Zipfian (θ=0.99). Same dataset as YCSB-A.\n\
     - **Mutation Log** — 25/25/25/25 allocate/read/update/delete mix, uniform random\n  \
       access. 10K records, sizes uniform in [64 B, 4 KiB].\n\
     - **Document Store** — 70/20/10 read/allocate/update mix, Zipfian (θ=0.7),\n  \
       log-normal value sizes (median 4 KiB, p99 ≈ 1 MiB). 10K records.\n"
}

/// Scenarios in the master-spec / build_scenarios order.
const SCENARIO_ORDER: &[&str] = &["ycsb-a", "ycsb-b", "mutation-log", "document-store"];

/// Engine modes, left-to-right in the table columns. Chisel first
/// because it's the subject of the comparison.
const ENGINE_MODES: &[&str] = &["chisel-strict", "redb-strict", "sqlite-strict"];

fn render_throughput_table(scenarios: &[ScenarioMetrics]) -> String {
    let mut out = String::new();
    out.push_str("## Throughput (ops/sec, higher is better)\n\n");
    out.push_str("| Scenario        | Chisel  | redb    | SQLite  |\n");
    out.push_str("| --------------- | ------- | ------- | ------- |\n");
    for &scenario in SCENARIO_ORDER {
        out.push_str(&format!("| {:<15} ", scenario));
        for &mode in ENGINE_MODES {
            let cell = lookup_scenario(scenarios, scenario, mode)
                .map(|m| format!("{:>7}", m.throughput_ops_per_sec.round() as u64))
                .unwrap_or_else(|| format!("{:>7}", "—"));
            out.push_str(&format!("| {} ", cell));
        }
        out.push_str("|\n");
    }
    out
}

fn render_p99_table(scenarios: &[ScenarioMetrics]) -> String {
    let mut out = String::new();
    out.push_str("## p99 latency per op (lower is better)\n\n");
    out.push_str("| Scenario        | Chisel    | redb      | SQLite    |\n");
    out.push_str("| --------------- | --------- | --------- | --------- |\n");
    for &scenario in SCENARIO_ORDER {
        out.push_str(&format!("| {:<15} ", scenario));
        for &mode in ENGINE_MODES {
            let cell = lookup_scenario(scenarios, scenario, mode)
                .map(|m| format_duration_ns(m.p99_ns))
                .unwrap_or_else(|| "—".to_string());
            out.push_str(&format!("| {:<9} ", cell));
        }
        out.push_str("|\n");
    }
    out
}

fn render_file_size_table(scenarios: &[ScenarioMetrics]) -> String {
    let mut out = String::new();
    out.push_str("## File size after workload (smaller is better)\n\n");
    out.push_str("| Scenario        | Chisel       | redb         | SQLite       |\n");
    out.push_str("| --------------- | ------------ | ------------ | ------------ |\n");
    for &scenario in SCENARIO_ORDER {
        out.push_str(&format!("| {:<15} ", scenario));
        for &mode in ENGINE_MODES {
            let cell = lookup_scenario(scenarios, scenario, mode)
                .map(|m| format_bytes_iec(m.final_file_size_bytes))
                .unwrap_or_else(|| "—".to_string());
            out.push_str(&format!("| {:<12} ", cell));
        }
        out.push_str("|\n");
    }
    out
}

fn render_methodology_footer() -> &'static str {
    // Path from bench/results/<UTC>/cross-engine.md to ARCHITECTURE.md
    // is three hops: out of UTC dir → bench/results → bench/ → repo root.
    "---\n\
     \n\
     Methodology: each cell is the result of a single end-to-end run of the\n\
     named scenario against the engine in strict durability mode. See\n\
     [`summary.md`](summary.md) in the same directory for the full per-cell\n\
     detail (p50, p95, total wall clock, file-size delta, and Chisel-internal\n\
     counter snapshots) and [the architecture doc](../../../ARCHITECTURE.md#benchmark-infrastructure)\n\
     for the bench-suite layout and workload definitions.\n\
     \n\
     The three engines do not perform equal work per commit, and the\n\
     throughput numbers should be read against that. Chisel's shadow-paging\n\
     protocol performs **three** fsyncs per commit (pre-drain flush, data\n\
     pages, then the superblock swap); redb commits at\n\
     `Durability::Immediate`; SQLite runs in WAL mode with\n\
     `synchronous=FULL`, plus `fullfsync=ON` so that on macOS it issues the\n\
     same `F_FULLFSYNC` Chisel does rather than a plain fsync. Numbers depend\n\
     on the platform's storage stack and are not portable across machine\n\
     classes.\n"
}

fn lookup_scenario<'a>(
    scenarios: &'a [ScenarioMetrics],
    scenario_name: &str,
    mode: &str,
) -> Option<&'a ScenarioMetrics> {
    scenarios
        .iter()
        .find(|s| s.scenario == scenario_name && s.mode == mode)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runner::ChiselCountersDelta;
    use crate::summary::metadata::MachineInfo;

    /// Display labels for the three engine columns — used to verify
    /// all three column headers appear in the rendered output.
    const ENGINE_LABELS: &[&str] = &["Chisel", "redb", "SQLite"];

    fn fixture_metadata() -> Metadata {
        Metadata {
            timestamp: "2026-05-04T12:00:00Z".to_string(),
            chisel_commit: "abc123de".to_string(),
            machine: MachineInfo {
                os: "linux".to_string(),
                arch: "x86_64".to_string(),
                hostname: "test-host".to_string(),
            },
            post_processor_version: "0.1.0",
            criterion_dir: "target/criterion".to_string(),
            aux_metrics_path: "bench/results/aux_metrics.jsonl".to_string(),
            cell_count: 0,
        }
    }

    fn fixture_scenario(
        scenario: &str,
        mode: &str,
        throughput: f64,
        p99_ns: f64,
        size: u64,
    ) -> ScenarioMetrics {
        ScenarioMetrics {
            scenario: scenario.to_string(),
            mode: mode.to_string(),
            total_wall_clock_ns: 15_000_000_000,
            op_count: 100_000,
            throughput_ops_per_sec: throughput,
            p50_ns: 100_000.0,
            p95_ns: 200_000.0,
            p99_ns,
            final_file_size_bytes: size,
            file_size_delta_bytes: 0,
            counters: if mode == "chisel-strict" {
                Some(ChiselCountersDelta {
                    cache_hits: 0,
                    cache_misses: 0,
                    fsync_calls: 0,
                    pages_allocated: 0,
                })
            } else {
                None
            },
        }
    }

    fn full_fixture() -> Vec<ScenarioMetrics> {
        let mut v = Vec::new();
        for scenario in SCENARIO_ORDER {
            for (mode, throughput) in [
                ("chisel-strict", 6500.0),
                ("redb-strict", 5500.0),
                ("sqlite-strict", 8000.0),
            ] {
                v.push(fixture_scenario(
                    scenario,
                    mode,
                    throughput,
                    250_000.0,
                    100 * 1024 * 1024,
                ));
            }
        }
        v
    }

    #[test]
    fn render_full_fixture_includes_all_tables() {
        let scenarios = full_fixture();
        let out = render_cross_engine_markdown(&scenarios, &fixture_metadata());

        assert!(
            out.starts_with("# Chisel Bench: Cross-engine comparison\n"),
            "missing top-level header:\n{out}"
        );
        assert!(
            out.contains("## Throughput (ops/sec, higher is better)"),
            "missing throughput section:\n{out}"
        );
        assert!(
            out.contains("## p99 latency per op (lower is better)"),
            "missing p99 section:\n{out}"
        );
        assert!(
            out.contains("## File size after workload (smaller is better)"),
            "missing file size section:\n{out}"
        );

        // All four scenarios appear.
        for scenario in SCENARIO_ORDER {
            assert!(
                out.contains(scenario),
                "missing scenario {scenario}:\n{out}"
            );
        }
        // All three engine column labels appear.
        for label in ENGINE_LABELS {
            assert!(out.contains(label), "missing engine {label}:\n{out}");
        }
    }

    #[test]
    fn render_empty_scenarios_emits_placeholder() {
        let out = render_cross_engine_markdown(&[], &fixture_metadata());
        assert!(
            out.contains("No scenario data available"),
            "empty input should emit placeholder:\n{out}"
        );
        // Tables MUST NOT appear.
        assert!(
            !out.contains("## Throughput"),
            "empty input should not emit throughput table:\n{out}"
        );
        assert!(
            !out.contains("## p99 latency"),
            "empty input should not emit p99 table:\n{out}"
        );
        assert!(
            !out.contains("## File size"),
            "empty input should not emit file size table:\n{out}"
        );
    }

    #[test]
    fn render_single_scenario_one_row_per_table() {
        let scenarios = vec![
            fixture_scenario(
                "ycsb-a",
                "chisel-strict",
                6500.0,
                250_000.0,
                100 * 1024 * 1024,
            ),
            fixture_scenario(
                "ycsb-a",
                "redb-strict",
                5500.0,
                320_000.0,
                110 * 1024 * 1024,
            ),
            fixture_scenario(
                "ycsb-a",
                "sqlite-strict",
                8000.0,
                195_000.0,
                95 * 1024 * 1024,
            ),
        ];
        let out = render_cross_engine_markdown(&scenarios, &fixture_metadata());

        // ycsb-a row appears in each table — count occurrences after the
        // table separator pattern.
        let ycsb_a_data_rows = out.matches("| ycsb-a").count();
        assert_eq!(
            ycsb_a_data_rows, 3,
            "expected 3 data rows (one per table) for ycsb-a:\n{out}"
        );
        // Other scenarios still appear in column headers / leftmost cells
        // but as "—" — actually they appear as rows because all 4 scenarios
        // are always rendered. Verify the missing scenarios show em-dash.
        assert!(
            out.contains("ycsb-b"),
            "ycsb-b row should still appear:\n{out}"
        );
        assert!(
            out.contains("—"),
            "missing data should show em-dash:\n{out}"
        );
    }

    #[test]
    fn render_missing_engine_renders_em_dash() {
        // Only chisel-strict data for ycsb-a; redb and sqlite cells must be em-dash.
        let scenarios = vec![fixture_scenario(
            "ycsb-a",
            "chisel-strict",
            6500.0,
            250_000.0,
            100 * 1024 * 1024,
        )];
        let out = render_cross_engine_markdown(&scenarios, &fixture_metadata());
        // Chisel's value should be present in throughput.
        assert!(
            out.contains("6500"),
            "chisel throughput value missing:\n{out}"
        );
        // The em-dash must appear (other engines).
        assert!(
            out.contains("—"),
            "missing-engine cells should render em-dash:\n{out}"
        );
    }

    #[test]
    fn render_includes_methodology_footer_and_summary_link() {
        let scenarios = full_fixture();
        let out = render_cross_engine_markdown(&scenarios, &fixture_metadata());
        assert!(
            out.contains("Methodology:"),
            "methodology footer missing:\n{out}"
        );
        assert!(
            out.contains("[`summary.md`](summary.md)"),
            "summary.md cross-link missing:\n{out}"
        );
        assert!(
            out.contains("the architecture doc"),
            "architecture link missing:\n{out}"
        );
        assert!(
            out.contains("../../../ARCHITECTURE.md#benchmark-infrastructure"),
            "architecture relative path wrong:\n{out}"
        );
    }
}
