# Type stubs for the chisel package.
#
# These describe the public surface exposed by `chisel/__init__.py`, which
# re-exports symbols from the compiled Rust extension (`chisel._chisel`) plus
# the three Python-side dataclasses (`Stats`, `DefragOptions`, `DefragStats`).
#
# Why the name is exactly `__init__.pyi`: PEP 561 resolves a stub by module
# path, so inside package `chisel` a file named `chisel.pyi` would be the stub
# for module `chisel.chisel` — which does not exist, leaving every declaration
# below inert. The stub for the package itself must be `__init__.pyi`. It sits
# next to `py.typed`, which marks the package as shipping its own types; a
# checker then reads this file in preference to `__init__.py`.
#
# Buffer protocol: we use `collections.abc.Buffer` (PEP 688, Python 3.12+).
# The package supports Python 3.11 at runtime, but type checkers running on
# 3.11 may need `typing_extensions.Buffer`; values still work fine at
# runtime because PyO3 accepts any buffer-protocol object.

import os
from collections.abc import Buffer, Iterable, Sequence
from dataclasses import dataclass
from types import TracebackType
from typing import Self

__version__: str


class ChiselError(Exception): ...
class OperationalError(ChiselError): ...
class FatalError(ChiselError): ...


# Operational errors — database state is intact; the caller made a mistake
# or hit a transient condition.
class InvalidHandleError(OperationalError): ...
class NoActiveTransactionError(OperationalError): ...
class TransactionAlreadyActiveError(OperationalError): ...
class SavepointNotFoundError(OperationalError): ...
class DuplicateSavepointError(OperationalError): ...
class ReadOnlyModeError(OperationalError): ...
class DatabaseFileNotFoundError(OperationalError): ...
class InvalidRootNameError(OperationalError): ...
class RootNameTableFullError(OperationalError): ...
class InvalidSuperblockCountError(OperationalError): ...
class InvalidArgon2ParamsError(OperationalError): ...
class CacheFullError(OperationalError): ...
class SpillwayFullError(OperationalError): ...
class TransactionInProgressError(OperationalError): ...
class ClosedError(OperationalError): ...
class AlreadyFinishedError(OperationalError): ...
class TagMismatchError(OperationalError): ...
# Encryption operational errors — database intact; caller supplied wrong or
# missing key material, or supplied a key to a plaintext database.
class NoEncryptionKeyError(OperationalError): ...
class InvalidEncryptionKeyError(OperationalError): ...
class EncryptionNotSupportedError(OperationalError): ...
# Key-rotation capacity/safety guards — database intact; caller hit a limit.
class NoFreeKeySlotError(OperationalError): ...
class LastKeySlotError(OperationalError): ...


# Fatal errors — database is poisoned or on-disk state is suspect.
# IoError also subclasses the builtin OSError, so a Chisel disk-level failure
# is catchable as `except OSError` (and `.errno` is OSError's native attribute).
class IoError(FatalError, OSError):
    # I42 (ISSUES.md, 2026-05-22): set by to_py_err when the underlying
    # ChiselError::IoError wraps a real std::io::Error. `errno` is the
    # platform's raw_os_error (e.g., 28 = ENOSPC on Linux); None if the
    # io::Error was synthesized without a real OS error code — populated via
    # OSError's native 2-arg (errno, strerror) constructor, so `.strerror` is
    # also set when an errno exists. `kind` is the string form of
    # std::io::ErrorKind (e.g., "PermissionDenied", "NotFound"), Chisel-specific
    # (no OSError equivalent) and attached best-effort via setattr.
    errno: int | None
    kind: str
class ChecksumMismatchError(FatalError): ...
class CorruptSuperblockError(FatalError): ...
class FileSizeMismatchError(FatalError): ...
class LockFailedError(FatalError): ...
class UnsupportedFormatVersionError(FatalError): ...
class UnsupportedPageSizeError(FatalError): ...
class CorruptPageError(FatalError): ...
class InvalidPageIdError(FatalError): ...
class PoisonedError(FatalError): ...
# Encryption fatal error: MAC verification failed on a page read after a
# successful open. Data integrity cannot be confirmed; treat as poison.
class DecryptionFailedError(FatalError): ...


@dataclass(frozen=True)
class Stats:
    handle_count: int
    total_pages: int
    file_size_bytes: int
    # I74: spillway capacity — None until the spillway is first opened
    # on an overflow spill. See chisel/__init__.py for the rationale on
    # None-vs-Some(0).
    spillway_logical_bytes: int | None = None
    spillway_max_bytes: int | None = None


@dataclass(frozen=True)
class Counters:
    cache_hits: int
    cache_misses: int
    pages_allocated: int
    fsync_calls: int


@dataclass(frozen=True)
class DefragOptions:
    sparse_threshold: float = 0.25
    max_values: int = 0


@dataclass(frozen=True)
class DefragStats:
    pages_examined: int = 0
    pages_freed: int = 0
    values_moved: int = 0


class DrainInsertion:
    # PyO3 pyclass enum mirroring chisel::DrainInsertion. Users reach for
    # `chisel.DrainInsertion.LruTail` / `chisel.DrainInsertion.Mru`; the
    # class-level attributes ARE the singleton instances. Variant names
    # match the Rust spelling so cross-referencing ARCHITECTURE.md
    # ADR-5 stays mechanical.
    LruTail: DrainInsertion
    Mru: DrainInsertion


def open(
    path: str | os.PathLike[str] | None = None,
    *,
    cache_max_bytes: int = 8_388_608,
    spillway_max_bytes: int | None = None,
    drain_insertion: DrainInsertion = ...,
    create_if_missing: bool = True,
    read_only: bool = False,
    superblock_count: int = 2,
    encryption_key: bytes | str | None = None,
) -> Chisel: ...


def rekey(path: str | os.PathLike[str], key: bytes | str) -> None:
    """Re-encrypt an entire database under a freshly generated data key.

    Takes a path rather than an open handle, and mirrors :func:`open` for that
    reason: it rewrites the whole file and replaces it by rename, so a handle
    opened beforehand would afterwards refer to the original, now-unlinked
    inode. Close any open database first, call this, then reopen.

    Use this only when the DATA key itself is believed compromised. If a
    credential leaked, :meth:`Chisel.rotate_key` is the right tool -- it is
    O(1) and touches only the superblock.

    Every credential other than ``key`` is revoked, because each key slot's
    wrapping key is derived from its own credential and only ``key`` was
    supplied. Add the others back with :meth:`Chisel.add_key` afterwards.

    For a passphrase credential the Argon2 cost parameters are INHERITED from
    the slot ``key`` currently unlocks, so a deliberately hardened database is
    not silently downgraded to the defaults by the rotation.

    Crash-safe: the rotated database is built beside the original and published
    with an atomic rename, so the path only ever names a complete file.

    Raises:
        DatabaseFileNotFoundError: no database at ``path``.
        EncryptionNotSupportedError: the database is not encrypted.
        InvalidEncryptionKeyError: ``key`` unlocks no key slot.
    """


class Chisel:
    @property
    def is_poisoned(self) -> bool: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...
    def close(self) -> None: ...

    def transaction(self) -> Transaction: ...
    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

    def allocate(self, value: Buffer) -> int: ...
    def read(self, handle: int) -> bytes: ...
    def update(self, handle: int, value: Buffer) -> None: ...
    def delete(self, handle: int) -> None: ...
    def delete_many(self, handles: Sequence[int]) -> None: ...

    def handles(self) -> Iterable[int]: ...

    def allocate_tagged(self, value: Buffer, tag: int) -> int: ...
    def tag(self, handle: int) -> int | None: ...
    def handles_with_tag(self, tag: int) -> list[int]: ...
    def delete_tagged(self, handle: int, tag: int) -> None: ...
    def delete_with_tag(self, tag: int, max: int) -> tuple[list[int], bool]: ...
    def client_byte(self, handle: int) -> int: ...
    def set_client_byte(self, handle: int, byte: int) -> None: ...

    def stats(self) -> Stats: ...
    def counters(self) -> Counters: ...

    def set_root_name(self, name: str, handle: int) -> None: ...
    def get_root_name(self, name: str) -> int | None: ...
    def clear_root_name(self, name: str) -> None: ...

    def defrag(self, options: DefragOptions | None = None) -> DefragStats: ...

    # Key-rotation methods. Each raises InvalidEncryptionKeyError if the
    # supplied existing/old/key does not unlock any slot. add_key and
    # rotate_key raise NoFreeKeySlotError if the 8-slot table is full;
    # remove_key raises LastKeySlotError if removing the key would leave
    # the database with no active encryption key.
    def add_key(self, existing: bytes | str, new: bytes | str) -> None: ...
    def rotate_key(self, old: bytes | str, new: bytes | str) -> None: ...
    def remove_key(self, key: bytes | str) -> None: ...

    # Between-transaction config mutators. Each raises
    # TransactionInProgressError if called mid-transaction.
    def set_cache_max_bytes(self, bytes: int) -> None: ...
    def set_spillway_max_bytes(self, bytes: int) -> None: ...
    def set_drain_insertion(self, policy: DrainInsertion) -> None: ...


class Transaction:
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def allocate(self, value: Buffer) -> int: ...
    def read(self, handle: int) -> bytes: ...
    def update(self, handle: int, value: Buffer) -> None: ...
    def delete(self, handle: int) -> None: ...
    def delete_many(self, handles: Sequence[int]) -> None: ...
    def allocate_tagged(self, value: Buffer, tag: int) -> int: ...
    def tag(self, handle: int) -> int | None: ...
    def handles_with_tag(self, tag: int) -> list[int]: ...
    def delete_tagged(self, handle: int, tag: int) -> None: ...
    def delete_with_tag(self, tag: int, max: int) -> tuple[list[int], bool]: ...
    def client_byte(self, handle: int) -> int: ...
    def set_client_byte(self, handle: int, byte: int) -> None: ...
    def set_root_name(self, name: str, handle: int) -> None: ...
    def get_root_name(self, name: str) -> int | None: ...
    def clear_root_name(self, name: str) -> None: ...
    def handles(self) -> list[int]: ...
    def stats(self) -> Stats: ...
    def counters(self) -> Counters: ...
    def defrag(self, options: DefragOptions | None = None) -> DefragStats: ...
    def savepoint(self, name: str) -> Savepoint: ...


class Savepoint:
    name: str
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...
    def release(self) -> None: ...
    def rollback_to(self) -> None: ...
