# Type stubs for the chisel package.
#
# These describe the public surface exposed by `chisel/__init__.py`, which
# re-exports symbols from the compiled Rust extension (`chisel._chisel`) plus
# the three Python-side dataclasses (`Stats`, `DefragOptions`, `DefragStats`).
#
# Why this file lives alongside __init__.py rather than at the package root:
# the stubs describe the `chisel` package namespace as users see it. The
# `py.typed` marker next to this file signals PEP 561 inline-typed package
# so type checkers pick these up.
#
# Buffer protocol: we use `collections.abc.Buffer` (PEP 688, Python 3.12+).
# The package supports Python 3.11 at runtime, but type checkers running on
# 3.11 may need `typing_extensions.Buffer`; values still work fine at
# runtime because PyO3 accepts any buffer-protocol object.

import os
from collections.abc import Buffer, Iterable, Sequence
from dataclasses import dataclass
from types import TracebackType
from typing import Self

__version__: str


class ChiselError(Exception): ...
class OperationalError(ChiselError): ...
class FatalError(ChiselError): ...


# Operational errors — database state is intact; the caller made a mistake
# or hit a transient condition.
class InvalidHandleError(OperationalError): ...
class NoActiveTransactionError(OperationalError): ...
class TransactionAlreadyActiveError(OperationalError): ...
class SavepointNotFoundError(OperationalError): ...
class DuplicateSavepointError(OperationalError): ...
class ReadOnlyModeError(OperationalError): ...
class DatabaseFileNotFoundError(OperationalError): ...
class InvalidRootNameError(OperationalError): ...
class RootNameTableFullError(OperationalError): ...
class InvalidSuperblockCountError(OperationalError): ...


# Fatal errors — database is poisoned or on-disk state is suspect.
class IoError(FatalError): ...
class ChecksumMismatchError(FatalError): ...
class CorruptSuperblockError(FatalError): ...
class FileSizeMismatchError(FatalError): ...
class InvalidMagicError(FatalError): ...
class LockFailedError(FatalError): ...
class UnsupportedFormatVersionError(FatalError): ...
class CorruptPageError(FatalError): ...
class InvalidPageIdError(FatalError): ...
class PoisonedError(FatalError): ...


@dataclass(frozen=True)
class Stats:
    handle_count: int
    total_pages: int
    file_size_bytes: int


@dataclass(frozen=True)
class DefragOptions:
    sparse_threshold: float = 0.25
    max_pages: int = 0


@dataclass(frozen=True)
class DefragStats:
    pages_examined: int = 0
    pages_freed: int = 0
    values_moved: int = 0


def open(
    path: str | os.PathLike[str] | None = None,
    *,
    cache_size: int = 1024,
    create_if_missing: bool = True,
    read_only: bool = False,
    superblock_count: int = 2,
) -> Chisel: ...


class Chisel:
    @property
    def is_poisoned(self) -> bool: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    def close(self) -> None: ...

    def transaction(self) -> Transaction: ...
    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

    def allocate(self, value: Buffer) -> int: ...
    def read(self, handle: int) -> bytes: ...
    def update(self, handle: int, value: Buffer) -> None: ...
    def delete(self, handle: int) -> None: ...
    def delete_many(self, handles: Sequence[int]) -> None: ...

    def handles(self) -> Iterable[int]: ...
    def stats(self) -> Stats: ...

    def set_root_name(self, name: str, handle: int) -> None: ...
    def get_root_name(self, name: str) -> int | None: ...
    def clear_root_name(self, name: str) -> None: ...

    def defrag(self, options: DefragOptions | None = None) -> DefragStats: ...


class Transaction:
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    def allocate(self, value: Buffer) -> int: ...
    def read(self, handle: int) -> bytes: ...
    def update(self, handle: int, value: Buffer) -> None: ...
    def delete(self, handle: int) -> None: ...
    def delete_many(self, handles: Sequence[int]) -> None: ...
    def set_root_name(self, name: str, handle: int) -> None: ...
    def get_root_name(self, name: str) -> int | None: ...
    def clear_root_name(self, name: str) -> None: ...
    def savepoint(self, name: str) -> Savepoint: ...


class Savepoint:
    name: str
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    def release(self) -> None: ...
    def rollback_to(self) -> None: ...
